---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.version }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "20Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.app.port }}
