---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    app: {{ include "app.name" . }}
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: {{ .Values.app.port }}
